#' @title get_symbols
#' @description get symbols for the slot machine
#' @details diamonds:DD,sevens: 7; triple bars:BBB; double bars:BB;one bar:B cherries:C and zeros:0
#'     This symbols are selected randomly, and each symbols appears
#'     with a different probability; look for functions body
#' @export
#' @examples \dontrun{
#'  set.seed(233)
#'  get_symbols()
#'  }
#'
#'
#'
get_symbols <- function(){
  wheel <- c("DD","7","BBB","BB","B","C","0")
  sample(wheel,3,replace=TRUE,
         prob = c(0.03,0.03,0.06,0.1,
                  0.25,0.01,0.52))
}
#' @title score
#' @description get score based in symbols generated by get_symbols
#'
#' @export
#' @examples \dontrun{
#' set.seed(24)
#' one_play <- get_symbols()
#' score(one_play)
#' }

score <- function(symbols) {

  bars <- symbols %in% c("B","BBB","BB")
  payouts <- c("DD"=100,"7"=80,"BBB"=40,"BB"=25,"B"=10,"C"=10,"0"=0)


  if(length(unique(symbols))==1) {
    prize <- unname(payouts[symbols[1]])
  } else if(all(bars)) {
    prize <- 5

  } else {
    # count cherries
    cherries <- sum(symbols == "C")
    prize <- c(0,2,5)[cherries+1]
  }
  diamonds <- sum(symbols == "DD")
  p <- prize * 2 ^ diamonds
  attr(p,"symbols") <- symbols
  p


}
#' @title play
#' @description generate score asociated to three symbols generated by slot machine
#'
#' @export
#' @examples  \dontrun{
#'  play()
#'}
play <- function() {
  symbols <- get_symbols()
  structure(score(symbols),symbols=symbols,class="slots")
}


